# Generated by Django 2.0.5 on 2018-06-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.FloatField()),
                ('distance', models.FloatField()),
                ('allowable_stress', models.FloatField()),
                ('unit_force', models.CharField(max_length=2)),
                ('unit_distance', models.CharField(max_length=2)),
                ('unit_allowable_stress', models.CharField(max_length=2)),
            ],
        ),
    ]
